## Week-7-LAB-12- Traffic prediction-using KNN

In [9]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [10]:
# Importing the training dataset
train_dataset = pd.read_csv('train_set.csv')

In [11]:
train_dataset.head()

Date     Day  CodedDay  Zone  Weather  Temperature  Trafficcnt
0  01/01/17  Sunday         7     1       21           17           1
1  01/01/17  Sunday         7     2       12           34           2
2  01/01/17  Sunday         7     3       25           24           2
3  01/01/17  Sunday         7     4       46           41           4
4  01/01/17  Sunday         7     5       33           19           3

In [12]:
train_dataset.shape

(52416, 7)

In [13]:
train_dataset.Trafficcnt.value_counts()

2    10814
5    10462
4    10400
1    10373
3    10367
Name: Trafficcnt, dtype: int64

In [14]:
train_dataset.drop(['Date','Day'],1, inplace=True)

C:\Users\Prof.Subhash chandra\AppData\Local\Temp\ipykernel_13212\3363662064.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  train_dataset.drop(['Date','Day'],1, inplace=True)


In [15]:
train_dataset.columns

Index(['CodedDay', 'Zone', 'Weather', 'Temperature', 'Trafficcnt'], dtype='object')

In [16]:
train_dataset.dtypes

CodedDay       int64
Zone           int64
Weather        int64
Temperature    int64
Trafficcnt     int64
dtype: object

In [17]:
train_dataset.head(2)

CodedDay  Zone  Weather  Temperature  Trafficcnt
0         7     1       21           17           1
1         7     2       12           34           2

In [18]:

X_train = train_dataset.iloc[:, [0,1,2,3]].values
y_train = train_dataset.iloc[:, 4].values


In [19]:
X_train

array([[  7,   1,  21,  17],
       [  7,   2,  12,  34],
       [  7,   3,  25,  24],
       ...,
       [  6, 142,  25,  12],
       [  6, 143,  24,  28],
       [  6, 144,  14,  24]], dtype=int64)

In [20]:
print(y_train)

[1 2 2 ... 3 1 1]


In [21]:
# Importing the testing dataset
test_dataset = pd.read_csv('test_set.csv')


In [22]:
test_dataset.head()

Date        Day  CodedDay  Zone  Weather  Temperature  Trafficcnt
0  01/06/18  Wednesday         3     2       35           17           2
1  01/06/18  Wednesday         3     3       36           16           3
2  01/06/18  Wednesday         3     4       27           25           5
3  01/06/18  Wednesday         3     5       23           23           3
4  01/06/18  Wednesday         3     6       18           42           2

In [23]:
test_dataset.drop(['Date','Day'],1, inplace=True)

C:\Users\Prof.Subhash chandra\AppData\Local\Temp\ipykernel_13212\2952939432.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  test_dataset.drop(['Date','Day'],1, inplace=True)


In [24]:
test_dataset.head()

CodedDay  Zone  Weather  Temperature  Trafficcnt
0         3     2       35           17           2
1         3     3       36           16           3
2         3     4       27           25           5
3         3     5       23           23           3
4         3     6       18           42           2

In [25]:
test_dataset.describe().T

count       mean        std  min   25%   50%    75%    max
CodedDay     1439.0   4.000695   1.733054  1.0   3.0   4.0    5.0    7.0
Zone         1439.0  72.549687  41.554330  1.0  37.0  73.0  108.5  144.0
Weather      1439.0  23.886032  13.576787  0.0  12.0  24.0   35.0   47.0
Temperature  1439.0  25.011119  11.325376  6.0  15.0  25.0   35.0   45.0
Trafficcnt   1439.0   3.031967   1.429018  1.0   2.0   3.0    4.0    5.0

In [26]:
X_test = test_dataset.iloc[:, [0,1,2,3]].values
y_test = test_dataset.iloc[:, 4].values

In [27]:
X_test

array([[  3,   2,  35,  17],
       [  3,   3,  36,  16],
       [  3,   4,  27,  25],
       ...,
       [  5, 142,  26,  38],
       [  5, 143,  16,  34],
       [  5, 144,  16,  17]], dtype=int64)

In [28]:
print(y_test)

[2 3 5 ... 1 3 1]


In [29]:
# Feature Scaling (Standardize features by removing the mean and scaling to unit variance.)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [30]:
X_train

array([[ 1.5       , -1.72006415, -0.17967827, -0.73733883],
       [ 1.5       , -1.69600731, -0.8311836 ,  0.73127039],
       [ 1.5       , -1.67195047,  0.10987965, -0.13261739],
       ...,
       [ 1.        ,  1.67195047,  0.10987965, -1.16928272],
       [ 1.        ,  1.69600731,  0.03749017,  0.21293772],
       [ 1.        ,  1.72006415, -0.68640463, -0.13261739]])

In [31]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 3, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [32]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

C:\Users\Prof.Subhash chandra\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [33]:
print(y_test[0])
print(y_pred[0])

2
2


In [34]:
# Making the Confusion Matrix
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)

In [35]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [36]:
from sklearn.metrics import f1_score
f1_score(y_test, y_pred, average='micro') 

0.5350938151494093

In [37]:
#new data prediction
newdata=[[3,2,35,17]]

classifier.predict(newdata)

C:\Users\Prof.Subhash chandra\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([1], dtype=int64)

In [38]:
# predict new trafic  [2,1,34,16] 2
#l=[3,2,35,17]

newdata = np.array([[3,3,33,16]])

print(classifier.predict(newdata))

[1]


C:\Users\Prof.Subhash chandra\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


Thank you