## NumPy arrays:

In [1]:
# install numpy 
!pip install numpy
#import numpy with an alias np


In [2]:
import numpy as np

In [3]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp

In [4]:
# creating a numpy array from a list data
data1 = [1, 2, 3, 4, 5]             # list
print(data1)
arr1 = np.array(data1)  

print("the array is:", arr1)
print(type(arr1))
# craeting a np array from list of lists


data2 = [range(1, 5), range(5, 9)]  # list of lists
arr2 = np.array(data2)              # 2d array
print(arr2)
#converting array to list using tolist()
arr2.tolist()    

[1, 2, 3, 4, 5]
the array is: [1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]]


[[1, 2, 3, 4], [5, 6, 7, 8]]

In [5]:
# printing a number using range 
for i in range(10): 
    print(i) 
print() 

0
1
2
3
4
5
6
7
8
9



In [6]:
#arange is like range, except it returns an array (not a list)
int_array = np.arange(5)
print(int_array)
print(type(int_array))
float_array = int_array.astype(float)
print(float_array)
print(type(float_array))

[0 1 2 3 4]
<class 'numpy.ndarray'>
[0. 1. 2. 3. 4.]
<class 'numpy.ndarray'>


In [7]:
# inspecting arrays
print(int_array.dtype)
print(float_array.dtype)
print(int_array.ndim)
data2 = [range(1, 5), range(5, 9)]  # list of lists
arr2 = np.array(data2)              # 2d array
print("the shape is:",arr2.shape)
print(arr2.size)
print(len(arr2))

int32
float64
1
the shape is: (2, 4)
8
2


In [8]:
#reshapping the array
arry1=np.arange(10, dtype=float)
print(arry1)
print(arry1.shape)
print(arry1)
arry2 = np.arange(10, dtype=float).reshape((5, 2))
print(arry2.shape)
print(arry2)
#print(arr.reshape(5, 2))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
(10,)
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
(5, 2)
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [9]:
#Flatten: always returns a flat copy of the orriginal array
# revist again with best example

arr1=np.arange(10)
print(arr1)
arr_flt=arr1.flatten()
print(arr_flt)
arr_flt[0] = 33
print(arr_flt)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[33  1  2  3  4  5  6  7  8  9]
[0 1 2 3 4 5 6 7 8 9]


In [10]:
## SLICING##

In [15]:
# slicing Syntax: start:stop:step with start (default 0) stop (default last) step (default 1)
#arr[0, :]
#arr[:, 0]
#arr[:, :2]
#arr1[:, 2:]
print(arr2)
#arr2 = arr1[1:2, 1:3]    # columns between index 1 (included) and 4 (excluded)
#print(arr2)

[[1 2 3]
 [4 5 6]]


In [12]:
# array selection and slicing
arr = np.arange(10, dtype=float).reshape((2, 5))
print('array is:','\n',arr)
print(arr[0])
print(arr[0,3])
print(arr[0][3])    
# 0th element (slices like a list)
# row 0, column 3: returns 4


array is: 
 [[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[0. 1. 2. 3. 4.]
3.0
3.0


In [13]:
#2-D arrays
import numpy as np
print("2-D Array")
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

2-D Array
[[1 2 3]
 [4 5 6]]


In [ ]:
##OPERATIONS ON ARRAY##

In [ ]:
#min and max of 2-D array
print(np.min(arr2))
print(np.max(arr2))

In [ ]:
arr2

In [ ]:
#all column mins
arr2.min(axis=0) #axis=0, refs to columns of nd-arrayrs

In [ ]:
#all row mins
arr2.max(axis=1) #axis=1, refs to rows of nd-arrayrs

In [ ]:
#all elements aggregates
np.sum(arr2)

### Array Shape and Re-shaping using NumPy

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("================================")
print("Shape of the array")
print(arr.shape)
print("================================")

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Before Reshape the array")
print(arr)
print("================================")
newarr = arr.reshape(4, 3)
print("After Reshape the array")      # reshape to 4 rows, 3 columns
print(newarr)
print("================================")



In [ ]:
                            ####Exercises  on IRIS dataset ###

In [ ]:
## Splitting arrays, Cocatenation of Arrays, Statistical operations (max, min, mean, sum , Standard deviation, transpose)